name: Deploy Jekyll site to Pages

on:
  # 触发条件：推送到 deploy 分支时运行工作流
  push:
    branches: ["deploy"]
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 设置 Ruby 环境
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"  # 根据 Jekyll 版本需要的 Ruby 版本调整

      # 安装依赖
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # 构建 Jekyll 网站
      - name: Build Jekyll site
        run: bundle exec jekyll build --baseurl "/jamboxx-infinite.github.io"
        env:
          JEKYLL_ENV: production

      # 上传生成的静态站点文件
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
